/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RelojesSin;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Observable;
import java.util.Observer;
import java.util.Random;

public class FrmGasolineraCliente extends javax.swing.JFrame implements Observer {

    
    public FrmGasolineraCliente() {
        initComponents();
        Cliente c = new Cliente(5000);
        c.addObserver(this);
        Thread t = new Thread(c);
        t.start();
        invi.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        Relojlocal = new javax.swing.JLabel();
        invi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cliente");

        jLabel4.setText("Horra servidor");

        Relojlocal.setText("jLabel5");

        invi.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(invi)
                    .addComponent(Relojlocal, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Relojlocal))
                .addGap(29, 29, 29)
                .addComponent(invi)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Random random = new Random();
        int millisInDay = 24 * 60 * 60 * 1000;
        Date dt = new Date((long) random.nextInt(millisInDay));
        SimpleDateFormat sdf24 = new SimpleDateFormat("HH:mm:ss");
        Calendar cal = Calendar.getInstance();
        /*
    if (invi.equals("")) 
    {
                cal.setTime(dt);
    } else {
                    try {
            Date d = new SimpleDateFormat("HH:mm:ss").parse(invi.getText());
            cal.setTime(d);
        } catch (ParseException ex) {
            Logger.getLogger(FrmGasolineraCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     */
        cal.setTime(dt);
        Runnable corre = new Runnable() {
            @Override
            public void run() {
                while (true) {
                    try {
                        Thread.sleep(1000);
                        cal.add(Calendar.SECOND, 1);
                        Date dat = cal.getTime();
                        String time24 = sdf24.format(dat);
                        Relojlocal.setText(time24);

                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        };
        // Creamos un hilo y le pasamos el runnable
        Thread tread = new Thread(corre);

        tread.start();

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmGasolineraCliente().setVisible(true);
            }
        }
        );

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Relojlocal;
    public static javax.swing.JLabel invi;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        String valor = (String) arg;
        Relojlocal.setText(valor + "");

    }

}
