/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reservacion;

import java.io.ByteArrayOutputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author JManuel
 */
public class PanelReloj extends javax.swing.JPanel {
    
    private Clock reloj;
    private InetAddress ip;
    private int port;
    private int latencia;

    public int getLatencia() {
        return latencia;
    }

    public void setLatencia(int latencia) {
        this.latencia = latencia;
    }
    /**
     * Creates new form PanelReloj
     */
    public PanelReloj() {
        initComponents();
    }
    
    public PanelReloj(String nombre){
        initComponents();
        labelTitulo.setText(nombre);
        reloj = new Clock(labelHora);
        reloj.start();
    }
    public PanelReloj(String nombre,int hora, int minutos,int segundos,int segundero){
        initComponents();
        this.ip = null;
        this.port = 0;
        labelTitulo.setText(nombre);
        reloj = new Clock(hora,minutos,segundos,labelHora,segundero);
        reloj.start();
    }
    public PanelReloj(String nombre,int hora, int minutos,int segundos,int segundero,InetAddress ip,int port){
        initComponents();
        this.ip = ip;
        this.port = port;
        labelTitulo.setText(nombre);
        reloj = new Clock(hora,minutos,segundos,labelHora,segundero);
        reloj.start();
    }
    
    public void ModificarReloj(int hora,int minutos,int segundos){
        reloj.setHora(hora);
        reloj.setMinutos(minutos);
        reloj.setSegundos(segundos);
    }

    public Clock getReloj() {
        return reloj;
    }

    public void setReloj(Clock reloj) {
        this.reloj = reloj;
    }

    public InetAddress getIp() {
        return ip;
    }

    public void setIp(InetAddress ip) {
        this.ip = ip;
    }

    public int getPort() {
        return port;
    }

    public void setPort(int port) {
        this.port = port;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelHora = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        labelTitulo.setText("Titulo");

        labelHora.setBackground(new java.awt.Color(153, 153, 255));
        labelHora.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelHora.setForeground(new java.awt.Color(255, 255, 255));
        labelHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHora.setText("00:00:00");
        labelHora.setOpaque(true);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTitulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelHora, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    //Solicitamos al cliente que detenga su reloj y mostramos ventana para cambiar hora
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        DataOutputStream output = new DataOutputStream(baos);
        try {
            //Enviamos solicitud de detener reloj
            ServidorReloj.SincronizarRelojes(false);
            output.writeInt(Servidor.DETENER_RELOJ);
            output.flush();
            byte[] b = baos.toByteArray();
            DatagramPacket paquete = new DatagramPacket(b,b.length,ip,port);
            DatagramSocket socket = new DatagramSocket();
            socket.send(paquete);
            reloj.Stop();
            System.out.println("Enviada peticion para detener reloj");
            socket.close();
            Modificar modificar = new Modificar(reloj);
            modificar.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(ServidorReloj.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnModificarActionPerformed
    //Enviamos la nueva hora y reanudamos reloj
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            DataOutputStream output = new DataOutputStream(baos);
            output.writeInt(Servidor.REANUDAR_RELOJ);
            output.flush();
            output.writeInt(reloj.ClockInSeconds());
            output.flush();
            byte[] b = baos.toByteArray();
            DatagramPacket paquete = new DatagramPacket(b,b.length,ip,port);
            DatagramSocket socket = new DatagramSocket();
            socket.send(paquete);
            reloj.Start();
            ServidorReloj.SincronizarRelojes(true);
            System.out.println("Enviada peticion reanudar reloj");
        } catch (IOException ex) {
            Logger.getLogger(PanelReloj.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labelHora;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
